import { readFile, writeFile, mkdir } from 'node:fs/promises';

const source = new URL('../src/chronolens.user.js', import.meta.url);
const output = new URL('../dist/chronolens.user.js', import.meta.url);
const code = await readFile(source, 'utf8');
const generated = code.replace(
  '// ==UserScript==',
  '// ==UserScript==\n// ChronoLens 1.0.0 — generated from src/chronolens.user.js. Do not edit this file directly.'
);
await mkdir(new URL('../dist/', import.meta.url), { recursive: true });
await writeFile(output, generated, 'utf8');
console.log(`Built ${output.pathname}`);
